*** Settings ***
Documentation    Common variables for testing

*** Variables ***
${REMOTE_URL}                      http://localhost:4723
${ANDROID_AUTOMATION_NAME}         UIAutomator2
${ANDROID_TEST_APP}                app/testApp.apk
${ANDROID_PLATFORM_NAME}           Android
${ANDROID_DEVICE_NAME}             emulator-5554

### ACCOUNT CREDENTIALS ###
${USERNAME}                        bod@example.com
${PASSWORD}                        10203040